import { PERMISSIONS } from './permissions'

export type SystemRoleName
  = | 'Superadmin'
    | 'Admin'
    | 'HQ Asset Manager'
    | 'Regional Technical Manager'
    | 'Technical Manager'
    | 'Service Centre Technician'
    | 'Finance Officer'
    | 'Stores Officer'
    | 'Auditor'
    | 'Viewer'

type SystemRoleMap = Record<Exclude<SystemRoleName, 'Superadmin'>, string[]>

export const SYSTEM_ROLES: SystemRoleMap = {
  'Admin': [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.ORG_UNIT_CREATE,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.ORG_UNIT_UPDATE,
    PERMISSIONS.ORG_UNIT_DELETE,
    PERMISSIONS.JOB_ROLE_CREATE,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.JOB_ROLE_UPDATE,
    PERMISSIONS.JOB_ROLE_DELETE,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_UPDATE,
    PERMISSIONS.REPORT_DELETE,
  ],
  'HQ Asset Manager': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.REPORT_READ,
  ],
  'Regional Technical Manager': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.REPORT_READ,
  ],
  'Technical Manager': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.REPORT_READ,
  ],
  'Service Centre Technician': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_UPDATE,
  ],
  'Finance Officer': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_UPDATE,
  ],
  'Stores Officer': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.REPORT_READ,
  ],
  'Auditor': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.REPORT_READ,
  ],
  'Viewer': [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.REPORT_READ,
  ],
}
