import { PERMISSIONS } from './permissions'

export type SystemRoleName = 'SUPERADMIN' | 'ADMIN' | 'REVIEWER' | 'EDITOR' | 'USER'

export const SYSTEM_ROLES: Record<Exclude<SystemRoleName, 'SUPERADMIN'>, string[]> = {
  ADMIN: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.ORG_UNIT_CREATE,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.ORG_UNIT_UPDATE,
    PERMISSIONS.JOB_ROLE_CREATE,
    PERMISSIONS.JOB_ROLE_READ,
    PERMISSIONS.JOB_ROLE_UPDATE,
  ],
  REVIEWER: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
  ],
  EDITOR: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORG_UNIT_READ,
    PERMISSIONS.JOB_ROLE_READ,
  ],
  USER: [
    PERMISSIONS.USER_READ,
  ],
}
